# NOTE: This Dockerfile is meant to be used from the mkdocker_xvfb.sh script.

# Pull a concrete version of Linux that does NOT recieve updates after it's
# been created.  This is so that the image is as stable as possible to make
# image creation reproducible.
# NB: this also means there may be no security-related fixes there, need to
# move the version to the next manually.

ARG ARCH_FROM
ARG ARCH=i386
ARG OS_NAME
ARG OS_VERSION

# jetbrains/runtime:jbrTest_${os_name}${os_version}-$arch
FROM ${ARCH_FROM}/${OS_NAME}:${OS_VERSION}

ARG ARCH
RUN \
    if [ "$ARCH" = "i386" ]; then \
      echo Installing packages required for i386 only; \
      dpkg --add-architecture i386; \
      apt-get update -y; \
      apt-get install -y \
          libc6:i386 \
          libncurses5 libncurses5:i386 \
          libstdc++6:i386 \
          zlib1g:i386; \
    else \
      echo Skipping the step installing packages specific for the platform; \
    fi; \
    apt-get update -y; \
    apt-get install -y \
        libgtk2.0-0:${ARCH} \
        libxext6:${ARCH} \
        libxi6:${ARCH} \
        libxrender-dev:${ARCH} \
        libxtst6:${ARCH} \
        libxrandr2:${ARCH} \
        libfreetype6:${ARCH} \
        fontconfig:${ARCH} \
        libnss3:${ARCH} \
        libatk-bridge2.0-0:${ARCH} \
        libgbm1:${ARCH} \
        libxkbcommon0:${ARCH} \
        libasound2:${ARCH};\
    apt-get clean all

ENV DISPLAY=:0

#ADD run_xvfb.sh /run_xvfb.sh
#RUN chmod a+x /run_xvfb.sh
#CMD /run_xvfb.sh

#        fontconfig:i386 \
#        x11-apps:i386; \


#    apt-get install -y \
#        libgtk2.0-0${LIB_ARCH_POSTFIX}\
#        libxext6${LIB_ARCH_POSTFIX} \
#        libxi6${LIB_ARCH_POSTFIX} \
#        libxrender-dev${LIB_ARCH_POSTFIX} \
#        libxtst6${LIB_ARCH_POSTFIX} \
#        xvfb${LIB_ARCH_POSTFIX}; \
