# NOTE: This Dockerfile is meant to be used from the mkdocker_aarch64.sh script.

# Pull a concrete version of Linux that does NOT recieve updates after it's
# been created.  This is so that the image is as stable as possible to make
# image creation reproducible.
# NB: this also means there may be no security-related fixes there, need to
# move the version to the next manually.

ARG ARCH
ARG OS_NAME
ARG OS_VERSION

# jetbrains/runtime:jbrTest_ubuntu20.04-arm64v8
FROM ${ARCH}/${OS_NAME}:${OS_VERSION}

# Install the necessary build tools
RUN apt-get update -y; \
    apt-get install -y \
        fontconfig \
        libgtk2.0-0 \
        libxext6 \
        libxi6 \
        libxrender-dev \
        libxtst6 \
        xvfb \
        x11-apps;\
   apt-get clean all

ENV DISPLAY=:0

ADD run_xvfb.sh /run_xvfb.sh
RUN chmod a+x /run_xvfb.sh
CMD /run_xvfb.sh

